"""
Django settings for phoenix project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-@7k4y0l%s#8c3l9_fzm*#lkln@@%%a+4ykfhw)ymty5z3d1ooc"

ALLOWED_HOSTS = ["*"]
load_dotenv()

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "phoenix",
    "message_consumer",
    "message_producer",
    "data_migrator",
    "embedding_generator",
    "similar_image_search",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "phoenix.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "phoenix.wsgi.application"

LOGGING_DIR = os.path.join(
    BASE_DIR, "logs"
)  # Create a 'logs' directory in your project

if not os.path.exists(LOGGING_DIR):
    os.makedirs(LOGGING_DIR)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s - %(levelname)s - %(name)s - %(funcName)s - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "%(levelname)s - %(message)s",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGGING_DIR, "debug.log"),
            "maxBytes": 1024 * 1024,  # 1 MB per file
            "backupCount": 5,  # Keep up to 5 backup files
            "formatter": "verbose",
        },
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    # "loggers": {
    #     "django.db.backends": {
    #         "handlers": ["console"],
    #         "level": "DEBUG",  # You can set it to 'INFO' or 'WARNING' depending on your needs
    #     },
    # },
    "root": {
        "handlers": ["file"],
        "level": os.environ.get("DEBUG_VALUE"),
    },
}

MESSAGE_CONSUMER_IMPLEMENTATION = "messaging.consumer.kafka_consumer.KafkaConsumer"
MESSAGE_PRODUCER_IMPLEMENTATION = "messaging.producer.kafka_producer.KafkaProducer"

DATABASE_ROUTERS = ["data_migrator.routers.database_router.ReadOnlyDBRouter"]

GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DEFAULT_DB_NAME"),
        "USER": os.environ.get("DEFAULT_DB_USER"),
        "PASSWORD": os.environ.get("DEFAULT_DB_PASSWORD"),
        "HOST": os.environ.get("DEFAULT_DB_HOST"),
        "PORT": os.environ.get("DEFAULT_DB_PORT"),
    },
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "NAME": "test",
    #     "USER": "postgres",
    #     "PASSWORD": "postgres",
    #     "HOST": "localhost",
    #     "PORT": "5432",
    # },
    "read_replica": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("READ_REPLICA_DB_NAME"),
        "USER": os.environ.get("READ_REPLICA_USER"),
        "PASSWORD": os.environ.get("READ_REPLICA_PASSWORD"),
        "HOST": os.environ.get("READ_REPLICA_HOST"),
        "PORT": os.environ.get("READ_REPLICA_PORT"),
    },
}

KAFKA_BOOTSTRAP_SERVERS_IP = os.environ.get("KAFKA_BOOTSTRAP_SERVERS")
# SECURITY WARNING: don't run with debug turned on in production!
